### PR TITLE
binarytrees.cr as translation of binarytrees.java

### PR DESCRIPTION
**Pull request by akzhan**
Your Java code by @Stuk4 is kind of trick disallowed by game rules (left, right and item in tree node instead of left and right only).

But I update crystal one to it (because current Crystal implementation already uses this trick but insufficiently effective).

### CODE REVIEW

**Comment by akzhan** [comment]
Also should note that converting item and so on to Int64 increases performance too. 

But code less readable so use Int32 here.

**Comment by akzhan** [comment]
C++ implementation runs faster than provided C.

**Comment by kostya** [comment]
i want to check it, but my gcc seems to old, and clang not compiled also, with some paths problems.

**Comment by akzhan** [comment]
You can drop make_unique with old C++11 syntax, by your wish.

```c++
left = std::unique_ptr<TreeNode>(new TreeNode(2 * item - 1, depth - 1));
```

**Pull request merged**
